---
title: "Week7, 2021"
author: 'Danielle Barnas'
date: "2/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
### Libraries ###
library(tidyverse)
library(tidytuesdayR)
library(here)
library(plotly)
library(scales)
library(htmlwidgets)

rm(list=ls())

### Bring in Data ###
tuesdata <- tt_load(2021, week = 7)

race_wealth <- tuesdata$race_wealth


### Data Analysis ###
glimpse(race_wealth)

static<-race_wealth %>% 
  ggplot(aes(x=year, y=wealth_family,
             color=race, fill=race)) +
  geom_bar(stat="identity", position="dodge", aes(color = race)) + 
  labs(color="Race", fill = "Race",
       x="Year", y="Average Family Wealth per Year") + 
  theme_bw()


race_wealth %>% 
  plot_ly(x=~year, y=~wealth_family,
          color=~race, fill=~race,
          type = "bar",
          text = ~paste0("Annual Family Income: $", # customize hover label text
                        comma(round(wealth_family),decimals = 2)),
          hovertemplate = paste('%{text}')) %>% 
  layout(title = "Annual Family Income", #change plot title
         xaxis = list(title = "Year"), #change x-axis title
         yaxis = list(title = "Annual Income (USD)")) #change y-axis title
```




